name: Modifyworld
main: ru.tehkode.modifyworld.bukkit.Modifyworld
version: '${project.version}'
author: [t3hk0d3, gravypod]
website: www.palmergames.com
description: World modification permission ruleset
